version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shop_api
    container_name: nodejs-app
    ports:
      - "3200:3200"
    depends_on:
      - cassandra
    environment:
      - NODE_ENV=production
    networks:
      app-network:
        ipv4_address: 192.168.93.21

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      app-network:
        ipv4_address: 192.168.93.20
    volumes:
      - ./my_cassandra_storage:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=ShopCluster
      - CASSANDRA_KEYSPACE=shop_ecamazon2
      - CASSANDRA_DC=datacenter1

networks:
  app-network:
    ipam: 
      driver: default
      config:
        - subnet: "192.168.93.0/24"

